export function initialBoard(){ const p=Array(25).fill(0);p[24]=2;p[13]=5;p[8]=3;p[6]=5;p[1]=-2;p[12]=-5;p[17]=-3;p[19]=-5;return {p,bar:0,enemyBar:0,off:0}; }
export function moves(b,d){
 const home=b.bar===0&&b.p.slice(7).every(n=>n<=0);const origins=b.bar?[25]:b.p.map((n,i)=>n>0?i:0).filter(Boolean);
 return origins.flatMap(from=>{const to=from-d;if(to>0)return b.p[to]>=-1?[{from,to,die:d}]:[];
 if(!home)return [];if(to===0||b.p.slice(from+1).every(n=>n<=0))return [{from,to:0,die:d}];return [];});
}
export function apply(b,m){const c={...b,p:[...b.p]};if(m.from===25)c.bar--;else c.p[m.from]--;if(m.to===0)c.off++;else {if(c.p[m.to]===-1){c.p[m.to]=0;c.enemyBar++;}c.p[m.to]++;}return c;}
export function turns(b,dice){function walk(s,ds,path){const next=[...new Set(ds)].flatMap(d=>moves(s,d).map(m=>({m,ds:ds.filter((x,i)=>i!==ds.indexOf(d))})));if(!next.length)return [path];return next.flatMap(({m,ds})=>walk(apply(s,m),ds,[...path,m]));}const all=walk(b,dice,[]);const len=Math.max(...all.map(a=>a.length));let best=all.filter(a=>a.length===len);if(len===1&&dice.length===2&&dice[0]!==dice[1]){const hi=Math.max(...best.map(a=>a[0].die));best=best.filter(a=>a[0].die===hi);}return best;}
export function score(b){return b.off*20+b.enemyBar*8+b.p.reduce((s,n,i)=>s+(n>=2?(i<=6?6:3):n===1?-2:0),0);}
export function notation(ms){return ms.map(m=>`${m.from===25?'bar':m.from}/${m.to===0?'off':m.to}`).join(' · ');}
export const exercises=[{id:'opening31',title:'Make a strong first move',category:'Opening moves',dice:[3,1],best:[{from:8,to:5,die:3},{from:6,to:5,die:1}],hint:'Your 5-point is a valuable home-board point. Can you bring two checkers together there?',explain:'8/5 and 6/5 makes your 5-point. This blocks your opponent’s entry and gives you a foundation for a prime.'},{id:'opening61',title:'Build your first prime',category:'Opening moves',dice:[6,1],best:[{from:13,to:7,die:6},{from:8,to:7,die:1}],hint:'Look for a way to make the bar point: point 7, just outside your home board.',explain:'13/7 and 8/7 makes the bar point. Along with your 6-point and 8-point, it creates a three-point prime.'},{id:'opening42',title:'Strengthen your home board',category:'Opening moves',dice:[4,2],best:[{from:8,to:4,die:4},{from:6,to:4,die:2}],hint:'Two builders can meet on your 4-point. Find a path for each die.',explain:'8/4 and 6/4 makes your 4-point, giving you a second closed point in your home board.'}];
